/*
 *  Copyright (C) 2005-2026 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

#include "OmniphonyConfig.h"

#include "filesystem/Directory.h"
#include "filesystem/File.h"
#include "filesystem/SpecialProtocol.h"
#include "utils/log.h"

#include <vector>

namespace ActiveAE
{

namespace
{

#if defined(TARGET_DARWIN)
constexpr const char* BRIDGE_NAME = "libreference_bridge.dylib";
#elif defined(TARGET_WINDOWS)
constexpr const char* BRIDGE_NAME = "reference_bridge.dll";
#else
constexpr const char* BRIDGE_NAME = "libreference_bridge.so";
#endif

constexpr const char* CONFIG_DIR = "special://temp/omniphony/";
constexpr const char* CONFIG_FILE = "special://temp/omniphony/config.yaml";

//! \brief Read a whole file, or return an empty string when absent.
std::string ReadFile(const std::string& vfsPath)
{
  XFILE::CFile file;
  std::vector<uint8_t> data;
  if (!file.LoadFile(vfsPath, data))
    return {};
  return std::string(data.begin(), data.end());
}

} // unnamed namespace

std::string COmniphonyConfig::FindBridge()
{
  // Same locations the engine itself is searched for, so an addon or package
  // that ships both is found without any configuration.
  const std::vector<std::string> candidates = {
      CSpecialProtocol::TranslatePath("special://xbmcbin/omniphony/") + BRIDGE_NAME,
      CSpecialProtocol::TranslatePath("special://xbmc/system/omniphony/") + BRIDGE_NAME,
      CSpecialProtocol::TranslatePath("special://home/omniphony/") + BRIDGE_NAME,
  };

  for (const auto& candidate : candidates)
  {
    if (XFILE::CFile::Exists(candidate))
      return candidate;
  }
  return {};
}

std::string COmniphonyConfig::Emit(const std::string& bridgePath)
{
  // Kodi owns this file outright. Values that are not yet driven by settings
  // are the engine defaults recommended for a living-room listener: a
  // room-sized stage rather than the engine's 1 m default, and the room
  // simulation that makes the image sit outside the head rather than inside
  // it. Settings-driven values arrive with the rest of the settings work.
  std::string yaml;
  yaml += "# Generated by Kodi. Do not edit: this file is rewritten whenever\n";
  yaml += "# the settings that feed it change.\n";
  yaml += "render:\n";
  yaml += "  bridge_path: " + bridgePath + "\n";
  yaml += "  binaural:\n";
  yaml += "    output_mode: binaural\n";
  yaml += "    hrir_source: saf\n";
  yaml += "    unit_scale_m: 3.0\n";
  yaml += "    head_radius_m: 0.0875\n";
  yaml += "    air_absorption: true\n";
  yaml += "    reflections: { enabled: true, room_width_m: 4.0, room_depth_m: 5.0,\n";
  yaml += "                   room_height_m: 2.7, level: 0.5 }\n";
  yaml += "    reverb: { enabled: true, level: 0.25, rt60_s: 0.35, predelay_ms: 20 }\n";
  return yaml;
}

std::string COmniphonyConfig::Resolve()
{
  const std::string bridge = FindBridge();
  if (bridge.empty())
  {
    CLog::Log(LOGWARNING,
              "Omniphony: no decoder bridge ({}) found; the engine cannot start without one",
              BRIDGE_NAME);
    return {};
  }

  const std::string wanted = Emit(bridge);
  const std::string path = CSpecialProtocol::TranslatePath(CONFIG_FILE);

  // Rewrite only on change. In steady state this is zero writes, which
  // matters on the flash storage these devices boot from.
  if (ReadFile(CONFIG_FILE) == wanted)
    return path;

  if (!XFILE::CDirectory::Exists(CONFIG_DIR) && !XFILE::CDirectory::Create(CONFIG_DIR))
  {
    CLog::Log(LOGERROR, "Omniphony: could not create {}", CONFIG_DIR);
    return {};
  }

  XFILE::CFile file;
  if (!file.OpenForWrite(CONFIG_FILE, true) ||
      file.Write(wanted.c_str(), wanted.size()) != static_cast<ssize_t>(wanted.size()))
  {
    CLog::Log(LOGERROR, "Omniphony: could not write {}", CONFIG_FILE);
    return {};
  }
  file.Close();

  CLog::Log(LOGINFO, "Omniphony: wrote {} (bridge {})", path, bridge);
  return path;
}

} // namespace ActiveAE
